language: node_js
node_js:
  - "0.12"
sudo: false
cache:
  directories:
    - node_modules
    - bower_components
    - typings

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_success:
  - npm run coveralls
