language: node_js
node_js:
  - "0.12"
sudo: false

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run build
  - npm test
after_success:
  - npm run coveralls
